# Generated by Django 4.2.2 on 2023-06-17 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
