# Generated by Django 4.2.2 on 2023-06-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_shippingorder_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingorder',
            old_name='order_from',
            new_name='vendor_name',
        ),
        migrations.RenameField(
            model_name='shippingorder',
            old_name='order_to',
            new_name='vendor_site',
        ),
        migrations.RemoveField(
            model_name='shippingorder',
            name='product_quantity',
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='expected_delivery_date_cmr',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shippingorder',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shippingorder',
            name='sending_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
