# Generated by Django 4.2.2 on 2023-06-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_order_from_shippingorder_vendor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingorder',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
